# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
name: Release

steps:
  - &docker-test
    name: license
    image: docker:dind
    pull: always
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    environment: &default-env
      DOCKER_BUILDKIT: "1"
    commands:
      - &requirements
        apk add make bash util-linux
      - &target
        make $${DRONE_STEP_NAME}

  - <<: *docker-test
    name: lint

  - <<: *docker-test
    name: test

  - name: release
    image: registry.sighup.io/fury/drone-github-release:latest
    pull: always
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - export GITHUB_RELEASE_TITLE="Welcome $${DRONE_TAG} release"
      - export GITHUB_RELEASE_NOTE="docs/releases/$${DRONE_TAG}.md"
      - drone-github-release
    when:
      event:
        - tag

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
